### PR TITLE
Support /terminal being hosted deeper than the web server root level

### LINKED ISSUE #142: Switch from /terminal to /terminalsocket assumes that /terminal was at the root of the URL
https://github.com/intersystems-community/webterminal/blob/c49b0ac1d2a98c6084598bcf1a65ce794a13b89e/src/client/js/server/index.js#L56-L61

This fails in a situation where a "real" web server is hosting Web Gateway connections to multiple InterSystems servers. For instance an IIS instance on a server named `webhost` configured with root applications `dev` and `test`, and the Web Gateway connecting `/dev` and `/test` URLs to different InterSystems servers.

The WebTerminal URL for the dev server would be `http://webhost/dev/terminal/` but the code above points the websocket to `ws://webhost/terminalsocket/WebTerminal.Engine.cls`

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #142, allowing WebTerminal to work on sites that configure a single web server to host apps for multiple InterSystems servers.

It also updates gulp to version 4 so it works with modern Node versions.

### CODE REVIEW

**Comment by ZitRos** [comment]
> @ZitRos FYI I'm also thinking of doing another PR so my [VS Code extension](https://openexchange.intersystems.com/package/webterminal-vscode) can work without the user having to edit the WebTerminal.Router class.

I'm supportive. At the time when development started, we didn't have VisualStudio code yet which I love (i.e. in general, a pipeline to work with external editors)

**Review by ZitRos — APPROVED** [review]

**Comment by ZitRos** [comment]
@gjsjohnmurray thanks a ton for the PR. I currently don't have an ability to validate the release, please do it yourself (try to install the old version and update from it through the UI as well).

**Comment by ZitRos** [comment]
The code looks good!

**Comment by gjsjohnmurray** [comment]
@ZitRos thanks for merging and releasing this. I confirmed that UI upgrade from 4.9.3 to 4.9.4 worked.

**Pull request merged**
